#!/bin/bash


SLACKROLE="${*}"
SUBROLE=`echo "${SLACKROLE}"|awk -F\. {'print $2'}`
. /etc/default/SYSconstants

chown root:root /var/cache/slack/roles.conf
chmod 770 /var/cache/slack/roles.conf

slacksum "${SLACKROLE}"

