#!/bin/bash


CWD=`pwd`
ARGS="${*}"
ROLE=`echo "${ARGS}"|awk -F\. {'print $1'}|grep -v "^[0-9]*_[0-9]*$"`
SUBROLEACTION=`echo "${ARGS}"|awk -F\. {'print $2'}|grep -v "^[0-9]*_[0-9]*$"`
ACTIONATTR=`echo "${ARGS}"|awk -F\. {'print $3'}|grep -v "^[0-9]*_[0-9]*$"`
export SCRIPTDIR=`dirname $0`
ROLEDIR=`dirname ${SCRIPTDIR}`
##PKGARGS=`echo "${ARGS}"|perl -p -e "s/\./\n/g"|grep ".=."`
test "X${PKGARGS}" != "X" && eval "${PKGARGS}"
PATCHES=`cat ${SCRIPTDIR}/PATCHES 2>/dev/null`
PKGS=`cat ${SCRIPTDIR}/PKGS 2>/dev/null|perl -p -e "s/\n/,/g"`
RESPONCE=`echo "${PKGS}"|head -1|sed -e "s|,||g"`
PKGBASE=`pkgparam ${RESPONCE} BASEDIR 2>/dev/null`
if [ "X${BASEDIR}" = "X" -a -d ./%BASEDIR% ] ; then
  BASEDIR="${PKGBASE}"
fi

. /etc/default/SYSconstants
##set -x
roleperms()
{
echo
echo setperms
${SCRIPTDIR}/roleperms
echo
}

setperms()
{
echo
echo setperms
${SCRIPTDIR}/setperms
echo
}

fixbasedir()
{
echo
echo fixbasedir
if [ -d ./%BASEDIR% ] ; then
  if [ "X${BASEDIR}" != "X" ] ; then
    cd ./%BASEDIR% || exit 0
    mkdir -p "${CWD}${BASEDIR}"
    find * -depth -print|cpio -pdmu "${CWD}${BASEDIR}"
    cd "${CWD}"
    rm -rf ./%BASEDIR%
  fi
  test -d ./%BASEDIR% && rm -rf ./%BASEDIR%
fi

}

fixmacropaths()
{
if [ "X${__HOSTSHORT}" != "X" ] ; then
  for i in `find * -name *%HOSTSHORT%*` ; do
    src="${i}"
    dest=`echo "${src}"|sed -e "s|%HOSTSHORT%|${__HOSTSHORT}|g"`
    mv "${src}" "${dest}"
  done
fi

if [ "X${__HOSTNAME}" != "X" ] ; then
  for i in `find * -name *%HOSTNAME%*` ; do
    src="${i}"
    dest=`echo "${src}"|sed -e "s|%HOSTNAME%|${__HOSTNAME}|g"`
    mv "${src}" "${dest}"
  done
fi

if [ "X${__ARCH}" != "X" ] ; then
  for i in `find * -name *%${__ARCH}%*` ; do
    src="${i}"
    dest=`echo "${src}"|sed -e "s|%${__ARCH}%||g"`
    mv "${src}" "${dest}"
  done
fi

}


fixsysupdate()
{
## setup the proper yum repo file


set -x
if [ "X${__OSNAME}" = "XLinux" ] ; then
  LSB_REL=`/usr/bin/lsb_release -a`
  ##test "X${*}" != "X" && ARG_CAT=`cat ${*} 2>/dev/null`
  ##test "X${ARG_CAT}" != "X" && LSB_REL="${ARG_CAT}"

  case "${LSB_REL}" in
     *Distributor*ID:*EnterpriseEnterprise*Description:*Enterprise*Linux*Enterprise*Linux*|*Distributor*ID:*OracleServer*Description:*Oracle*Linux*Server*release*6*)
       DISTRO="OEL"
       mv etc/yum.repos.d/sysupdate.repo.OEL etc/yum.repos.d/sysupdate.repo
     ;;
     *Distributor*ID:*RedHatEnterpriseServer*Description:*Red*Hat*Enterprise*Linux*Server*release*5\.*)
       DISTRO="RHEL"
       mv etc/yum.repos.d/sysupdate.repo.RHEL etc/yum.repos.d/sysupdate.repo
     ;;
     *Distributor*ID:*OracleVMserver*Description:*Oracle*VM*server*release*2.2*)
       DISTRO="OVM22"
       mv etc/yum.repos.d/sysupdate.repo.OVM22 etc/yum.repos.d/sysupdate.repo
  esac
fi

REPOS=`ls -d etc/yum.repos.d/sysupdate.repo.* 2>/dev/null`
if [ "X${REPOS}" != "X" ] ; then
  perl -p -i -e "s|^enabled=*.*$|enabled=0|g" ${REPOS}
  cat ${REPOS} > etc/yum.repos.d/other.distros.sysupdate.repo
fi

## set the proper update repo hostname dependant on which network you are on
if [ "${__SITE}" = "ppa" ]; then
  perl -pi -e "s/%SHORTSUPPORT%/${__SUPPORTdr1}/g" opt/SYSpca-client/pca.conf 2>/dev/null
  perl -pi -e "s|%SHORTSUPPORT%|${__SUPPORTdr1}|g" etc/yum.repos.d/* 2>/dev/null
else
  perl -pi -e "s/%SHORTSUPPORT%/${__SHORTSUPPORT}/g" opt/SYSpca-client/pca.conf 2>/dev/null
  perl -pi -e "s|%SHORTSUPPORT%|${__SHORTSUPPORT}|g" etc/yum.repos.d/* 2>/dev/null
fi


find "${ROLEDIR}" -name sysupdate.repo.* -exec /bin/rm {} \;


}


fixsysupdate
fixfiler "${ARGS}"

##case "${SUBROLEACTION}${ACTIONATTR}" in
##  config)
##    roleperms
##    fixbasedir
##    fixmacropaths
##    exit 0
##  ;;
##
##  *)
##    roleperms
##    fixbasedir
##    fixmacropaths
##    setperms
##    exit 0
##esac
chmod 400 ${SCRIPTDIR}/%FETCHCRED%
chown root:root ${SCRIPTDIR}/%FETCHCRED%

exit 0
