#!/bin/bash


set -x
test -f /etc/yum/pluginconf.d/rhnplugin.conf && perl -p -i -e "s|^enabled.*$|enabled=0|g" /etc/yum/pluginconf.d/rhnplugin.conf 
test -f /sbin/chkconfig && /sbin/chkconfig --level 0123456 yum-updatesd off
test -f /etc/init.d/yum-updatesd && {
  /etc/init.d/yum-updatesd stop
  sleep 1
  /etc/init.d/yum-updatesd stop
  }
  

DIRTYREPOS="ULN-Base.repo*
epel-5-openscap.repo
yum-SYS-CentOS.repo
yum-SYS-rhel.repo
CentOS-Base.repo
CentOS-Debuginfo.repo
CentOS-Media.repo
CentOS-Vault.repo
SYS-rhn.repo*
mindtouch.repo*
mrepo.repo*
public-yum-el5.repo*
public-yum-ovm2.repo*
rhel-debuginfo.repo*
rhel-source.repo*
update-yum.repo*
yum-ovm2.repo*"

FQDIRTYREPOS=`echo "${DIRTYREPOS}"|awk '{if ($1 != "" ) {print "/etc/yum.repos.d/"$1}}'`

EXIST=`ls -d ${FQDIRTYREPOS} 2>/dev/null`
test "X${EXIST}" != "X" && rm -f ${EXIST}
set +x

export __DATESTRING=`date +%m_%d_%Y_%H_%M_%S`
DATESTRING="$__DATESTRING"
SUBROLE=`echo "${*}"|awk -F\. {'print $2'}|perl -p -e "s/\%.*//g"`
PWD=`pwd`
####export SYSTEM="${PWD}/%FETCHCRED%"
####chown root:root ${SYSTEM}
####chmod 400 ${SYSTEM}
ARGS="${*}"
ROLENAME=`echo "${ARGS}"|awk -F\. {'print $1'}`
POSTENV=`echo "${ARGS}"|perl -p -e "s/\%/\n/g"|grep "^..*=..*"|awk -F\. {'print $1'}`
set +x

. /etc/default/SYSconstants
set -x

test "X${POSTENV}" != "X" && eval export "${POSTENV}"

##/usr/sbin/slack --no-sync --no-scripts ${ROLENAME}.${__OSNAME}

IDTEST=`id|grep -i "^uid=0(root)"`
if [ "X${?}" = "X0" ] ; then
 CURRCRON=`crontab -l`
 UPDATECRON='# sysupdate: download system updates
0 * * * * ( . /etc/profile;. /etc/default/admin-functions;__slapjob ) >/dev/null 2>&1'

 UPDATETEST=`echo "${CURRCRON}"|grep ';__slapjob ).*>/dev/null .*2>&1$'`
 UPDATESTATUS="$?"
 if [ "X${UPDATESTATUS}" != "X0" ] ; then
  crontab -l >/var/tmp/currcron$$
  crontab -l|grep -v ';__slapjob$'|grep -v '^# .*sysupdate:'|grep -v ';__slapjob .*' >/var/tmp/cronedit$$
  echo "${UPDATECRON}" >>/var/tmp/cronedit$$
  sleep 1
  crontab /var/tmp/cronedit$$
 fi
fi  



  
case "${__OSNAME}" in
 SunOS)
  PATCHFILECKSUM=`cksum /opt/unix_ops/etc/SYScurrrev.xref 2>&1`
  STATUS=$?
  if [ "${STATUS}" = "0" ] ; then
   PATCHFILECKSUM=`echo "${PATCHFILECKSUM}"|awk {'print $1"."$2'}`
   headerdate=`head -1 /opt/unix_ops/etc/SYScurrrev.xref|grep "PATCHDIAG"|perl -p -e "s/\#//g"|awk {'print $NF'}|perl -p -e "s/\//\_/g"`
   if [ "X${headerdate}" != "X" ] ; then
    destfilename="patchdiag.xref.${headerdate}.${PATCHFILECKSUM}"
   else
    destfilename="patchdiag.xref.${PATCHFILECKSUM}"
   fi
   mv /opt/unix_ops/etc/SYScurrrev.xref /opt/unix_ops/etc/${destfilename}.xref
  fi

  cd /opt/unix_ops/etc/ && ln -sf ./${destfilename}.xref ./SYScurrrev.xref
  cd /opt/unix_ops/etc/ && ln -sf ./SYScurrrev.xref ./patchdiag.xref 
 ;;

 Linux)
  echo foo
 ;;

 *)
  echo "unknown OS"
  exit 1
esac

echo "${__HOSTNAME}"|$__GREP -E '(^none|^localhost)' >/dev/null
JUMPSTATUS="$?"
if [ "X${JUMPSTATUS}" = "X1" ] ; then

 case "${SUBROLE}" in
       stig)
         mkdir -p /opt/unix_ops/log
         echo 
         echo "tail -f /opt/unix_ops/log/STIG.watch.${DATESTRING}.out"
         cd /tmp
         /usr/bin/nohup /opt/unix_ops/bin/stig  > "/opt/unix_ops/log/STIG.watch.${DATESTRING}.out" 2>&1 < /dev/null &
         echo 
         exit 0
       ;;
       run)
## if [ "X${OSNAME}" = "XSunOS" ] ; then
## (cd /opt/unix_ops && ./pca -X `pwd` -y -i missingrs >./pca.out.${DATESTRING} 2>&1;cat ./pca.out.${DATESTRING}|mailx -s "pca.run ${__HOSTNAME}" ${__SUDO_USER_MAIL} 2>&1 >/dev/null;/usr/sbin/slack-get sysupdate.report%__SUDO_USER=${__SUDO_USER}) >/dev/null 2>/dev/null < /dev/null &
##
##  /usr/bin/nohup -p $!
## elif [ "X${OSNAME}" = "XLinux" ] ; then
##
##  UPDATELIST=`/usr/bin/yum check-update|grep -v -E '(\[|\])'|grep -- '-'`
##
##  if [ "X${UPDATELIST}" != "X" ] ; then
##   UPDATEQTY=`echo "${UPDATELIST}"|wc -l|awk {'print $1'}`
##  else
##   UPDATEQTY='0'
##  fi
## 
##  OELSYNCDATE=`cat /opt/unix_ops/etc/SyncDate 2>/dev/null`
##  if [ "X${OELSYNCDATE}" = "X" ] ; then
##   OELSYNCDATE='foo'
##  fi
## 
##  printf "Using repodata from ${OELSYNCDATE}\nHost: ${__HOSTNAME} (${__OSNAME}/`uname -r`/${__ARCH})\nList: check-update (${UPDATEQTY}/9999)\n\n" >"/opt/unix_ops/yum.out.${DATESTRING}"
##  nohup /usr/bin/yum -y update >>"/opt/unix_ops/yum.out.${DATESTRING}" 2>&1 &
## fi
##  /usr/bin/nohup /opt/unix_ops/bin/run  >/dev/null 2>/dev/null < /dev/null &
####read foo
##set -x
  NEEDZONEPATCHING=`/usr/sbin/zoneadm list -cv 2>/dev/null`
  test "X$?" = "X0" && {
    NEEDZONEPATCHING=`/usr/sbin/zoneadm list -cv 2>/dev/null|awk {'print $2" "$3'}|grep -v "^NAME STATUS$"|grep -v "^global "|grep -v " configured$"`
    ZNAME=`/usr/bin/zonename`
    }
  test "X${ZNAME}" = "Xglobal" -a "X${NEEDZONEPATCHING}" != "X" && {
    NEEDDETACH=`echo "${NEEDZONEPATCHING}"|awk '{if ($2 == "installed" ) {print "/usr/sbin/zoneadm -z "$1" detach"}}'`
  }

  test "X${NEEDDETACH}" != "X" && eval "${NEEDDETACH}"

  sleep 4

  NEEDDETACH=''
  NEEDZONEPATCHING=`/usr/sbin/zoneadm list -cv 2>/dev/null`
  test "X$?" = "X0" && {
    NEEDZONEPATCHING=`/usr/sbin/zoneadm list -cv 2>/dev/null|awk {'print $2" "$3'}|grep -v "^NAME STATUS$"|grep -v "^global "|grep -v " configured$"`
    ZNAME=`/usr/bin/zonename`
    }
  test "X${ZNAME}" = "Xglobal" -a "X${NEEDZONEPATCHING}" != "X" && {
    NEEDDETACH=`echo "${NEEDZONEPATCHING}"|awk '{if ($2 == "installed" ) {print "/usr/sbin/zoneadm -z "$1" detach"}}'`
  }


  test "X${NEEDDETACH}" != "X" && echo "${NEEDDETACH}"


  test "X${NEEDZONEPATCHING}" = "X" && {
    cd /tmp
    /usr/bin/nohup /opt/unix_ops/bin/run  >/dev/null 2>/dev/null < /dev/null &
    exit 0
    }

  test "X${NEEDZONEPATCHING}" != "X" && {
    cd /tmp
    /usr/bin/nohup /opt/unix_ops/bin/run -G  >/dev/null 2>/dev/null < /dev/null &
    test "X${ZNAME}" = "Xglobal" && {
      set +x
      sleep 3
      echo
      echo
      echo "##################################################"
      echo "##################################################"
      echo "## warning: this systems has attached zones...  ##"
      echo "## ..installing currentzone only patches.  Once ##"
      echo "##   these patches complete, you must 'halt'    ##"
      echo "##   and 'detach' these zones then 're-patch'   ##"
      echo "##   inorder to install remaining patches.      ##"
      echo "##################################################"
      echo "##################################################"
      echo
      }
    exit 0
    }

######  /opt/unix_ops/bin/run
              ;;
       report)
  set -x
  HOSTNAME="${__HOSTNAME}"
  SYSUPDATE="/opt/unix_ops"
  CURRRUN="/opt/${DATESTRING}"
  SPOOL="${SYSUPDATE}/spool"
  REPORT_D="${SYSUPDATE}/report.d"
  REPORT="${SYSUPDATE}/report"
  REPORTZIP="${REPORT}/sysupdate.report.zip"
  REPORTARCHIVEZIP="${REPORT}/sysupdate.report.archive.zip"
  LDIFDIR="${SYSUPDATE}/ldif" 
  PCACLIENT="/opt/unix_ops/bin"
  PCAETC="/opt/unix_ops/etc"
  MYRPTDIR="${PCACLIENT}/../log"

  if [ -f "${REPORTARCHIVEZIP}" ] ; then
    REPORTARCHIVESIZE=`ls -al "${REPORTARCHIVEZIP}"|awk {'print $5'}`
  fi

  if [ "X${REPORTARCHIVESIZE}" = "X" ] ; then
    REPORTARCHIVESIZE='0'
  fi

  if [ "${REPORTARCHIVESIZE}" -gt '4000000' ] ; then
    rm "${REPORTARCHIVEZIP}"
  fi

  rm -rf "${SPOOL}"
  mkdir -p "${SPOOL}"
  for i in ${REPORT_D}/* ; do
    echo "#### running ${i} ####"
    . ${i}
  done

  cd "${SPOOL}"
  CURRCKSUM=`cksum *|sort -u|cksum - |awk {'print $1" "$2'}`
  CURRUNDIR=`echo "${CURRCKSUM}"|awk {'print $1"_"$2'}`
  mkdir -p /opt/unix_ops/report
  cd "${SPOOL}" && rm -rf ${REPORTZIP} && echo "DESC: sysupdate.report
CKSUM: ${CURRCKSUM}
SUDO_USER: ${__SUDO_USER}"|zip -q -X -z ${REPORTZIP} *
  cd /opt && ln -s ./unix_ops ./${CURRUNDIR} && zip -qrm ${REPORTARCHIVEZIP} ./${CURRUNDIR} -i ./${CURRUNDIR}/spool/* ./${CURRUNDIR}/report.d/* && rm ./${CURRUNDIR}

  CKSUMSEARCH=`__ldapsearchhandler -x -b "ou=${__HOSTNAME},ou=hosts,${__LDAPDN}" hostcksum modifytimestamp`
  SEARCHSTATUS=$?
  if [ "X${SEARCHSTATUS}" = "X0" ] ; then
   TIMESTAMP=`echo "${CKSUMSEARCH}"|grep "^modifytimestamp:"`
   CKSUMINLDAP=`echo "${CKSUMSEARCH}"|grep "^hostcksum:"`
   CKSUMSTATUS=$?
   if [ "X${CKSUMSTATUS}" = "X0" ] ; then
    CKSUMINLDAP=`echo "${CKSUMINLDAP}"|perl -p -e "s/^hostcksum://g"|awk {'print $1" "$2'}`
    TIMESTAMP=`echo "${TIMESTAMP}"|perl -p -e "s/^modifytimestamp://g"|awk {'print $1'}|perl -p -e "s/Z$//g"|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{2\}\)/\1\|\2/;ta'|awk -F\| {'print $1$2" "$3" "$4" "$5" "$6" "$7" "$8'}`
    if [ -f "${__GAWK}" ] ; then
      AMIDLE=`echo "${TIMESTAMP}"|${__GAWK} ' {if(systime() - mktime($1" "$2" "$3" "$4" "$5" "$6" "$7) > 1209600) {print $1" "$2" "$3" "$4" "$5" "$6" "$7}}'|grep '.'`
    else
      AMIDLE=""
    fi
   else
    CKSUMINLDAP=NOCKSUM
   fi
  else
   CKSUMINLDAP=NOHOSTENTRY
  fi
  if [ "X${CKSUMINLDAP}" = "X${CURRCKSUM}" -a "X${AMIDLE}" = "X" ] ; then
   echo "no system changes... doing nothing"
   exit 0
  else
   CKSUM="${CURRCKSUM}"
   reporttemplate
  fi
      ;;
      *)
  exit 0
 esac
elif [ "X${JUMPSTATUS}" = "X0" -a "X${SUBROLE}" = "Xrun" ] ; then
 (cd /opt/unix_ops && ./pca -X `pwd` -y -i missingrs >./pca.out.${DATESTRING} 2>&1) >/dev/null 2>/dev/null < /dev/null &

 /usr/bin/nohup -p $!

fi

exit 0



