#!/bin/bash


##set -x
ARGS="${*}"
##echo "${ARGS}" >/tmp/ARGS
##exit

ROLE=`echo "${ARGS}"|awk -F\. {'print $1'}|grep -v "^[0-9]*_[0-9]*$"`
test "X${ROLE}" = "X" && exit 6
SUBROLEACTION=`echo "${ARGS}"|perl -p -e "s|\%.*$||g"|awk -F\. {'print $2'}|grep -v "^[0-9]*_[0-9]*$"|grep -v ".=."`
ACTIONATTR=`echo "${ARGS}"|perl -p -e "s|\%.*$||g"|awk -F\. {'print $3'}|grep -v "^[0-9]*_[0-9]*$"|grep -v ".=."`
PKGARGS=`echo "${ARGS}"|perl -p -e "s|\%.*$||g"|perl -p -e "s/\./\n/g"|grep ".=."`
export SCRIPTDIR=`dirname $0`
ROLEDIR=`dirname ${SCRIPTDIR}`
PATCHES=`cat ${SCRIPTDIR}/PATCHES 2>/dev/null`
PKGS=`cat ${SCRIPTDIR}/PKGS 2>/dev/null|perl -p -e "s/\n/,/g"`
RESPONCE=`echo "${PKGS}"|head -1|sed -e "s|,||g"`
##exit 1

/usr/sbin/slack-slaper global-slack
/usr/sbin/slack-slaper global-solaris-adminfunctions

. /etc/default/SYSconstants
mkdir -p "${ROLEDIR}/files" >/dev/null 2>&1
slack --no-sync --no-scripts -r "${ROLEDIR}/files" "${ROLE}.${__OSNAME}"
chmod 400 ${SCRIPTDIR}/%FETCHCRED%
chown root:root ${SCRIPTDIR}/%FETCHCRED%
NAME="${ROLE}Tracker"
DESC="DO NOT REMOVE THIS TRACKER PKG.  Ran ${ROLE} role."
if [ "X${__OSNAME}" = "XSunOS" ] ; then
  test -d /var/sadm/pkg/TRK${NAME}
  TRACKER="$?"
  if [ "X${PKGARGS}" = "X" -a -d "${ROLEDIR}/files/%BASEDIR%" ] ; then
    PKGBASE=`pkgparam ${RESPONCE} BASEDIR 2>/dev/null`
    if [ "X${PKGBASE}" != "X" ] ; then
      PKGARGS="BASEDIR=${PKGBASE}"
    fi
  fi
else
  rpm -q TRK${NAME} >/dev/null
  TRACKER="$?"
fi


main()
{
case "${SUBROLEACTION}${ACTIONATTR}" in
  "")
    echo
    echo "##################################"
    echo "##  Insufficient arguments (0)  ##"
    echo "##################################"
    echo
    roleusage
    return 2
  ;;    

  run|report)
    sysupdate.prepare
    return 0
  ;;

  *)
    ##set -x
    echo
    echo "########################"
    echo "##  INVALID ARGUMENT  ##"
    echo "########################"
    echo
    roleusage
    return 7
esac
}


appremove()
{
echo
echo "############"
echo "# REMOVING #"
echo "############"
echo "${PKGS}"
set -x
sleep 4
rm_pkgs ${PKGS}
set +x
echo "###########"
echo "# REMOVED #"
echo "###########"

}

mkusers()
{
echo 
echo mkuser
${SCRIPTDIR}/mkusers
echo
}

setperms()
{
echo
echo setperms
${SCRIPTDIR}/setperms
echo
}

cleanexit()
{
echo
echo cleanexit
if [ "X${ROLEDIR}" != "X" ] ; then
  ##set -x
  FILEPATHS=`ls -d ${ROLEDIR}/files ${ROLEDIR}/files.* ${ROLEDIR}/scripts 2>/dev/null`
  test "X${FILEPATHS}" != "X" && rm -rf ${FILEPATHS} 2>/dev/null
  test "X${FILEPATHS}" != "X" && mkdir -p ${FILEPATHS} 2>/dev/null
  ##set +x
else
  exit $1
fi
}


sysupdate.prepare()
{

case "${__OSNAME}" in
 SunOS)
  if [ -L /opt/SYSpca-client/SYScurrrev.xref ] ; then
   rm -f /opt/SYSpca-client/SYScurrrev.xref
  else
   PATCHFILECKSUM=`cksum /opt/SYSpca-client/SYScurrrev.xref 2>&1`
   STATUS=$?
   if [ "${STATUS}" = "0" ] ; then
    PATCHFILECKSUM=`echo "${PATCHFILECKSUM}"|awk {'print $1"."$2'}`
    headerdate=`head -1 /opt/SYSpca-client/SYScurrrev.xref|grep "PATCHDIAG"|perl -p -e "s/\#//g"|awk {'print $NF'}|perl -p -e "s/\//\_/g"`
    if [ "X${headerdate}" != "X" ] ; then
     destfilename="patchdiag.xref.${headerdate}.${PATCHFILECKSUM}"
    else
     destfilename="patchdiag.xref.${PATCHFILECKSUM}"
    fi
    mv /opt/SYSpca-client/SYScurrrev.xref /opt/SYSpca-client/${destfilename}.xref
   fi
  fi
 ;;

 Linux)
  reposdisable=`ls -d /etc/yum.repos.d/* 2>/dev/null|sort|grep -v "\/sysupdate.repo$"`
  test "X${reposdisable}" != "X" && perl -p -i -e "s|^enabled=1$|enabled=0|g" ${reposdisable}
 ;;
 *)
  echo "unknown OS"
  exit 1
 
esac 
}


roleusage()
{
if [ "X${ROLE}" != "X" ] ; then
  echo
  echo
  echo "################################################################################"
  echo "################################################################################" 
  echo "##  usage: ${ROLE}.run                ## patch/update the system      "
  echo "################################################################################"
  echo "################################################################################" 
  echo
fi
}


main || cleanexit $?

